version: "3.3"
services:
  nginx:
    image: quay.io/azavea/districtbuilder-nginx:${TRAVIS_COMMIT}
  django:
    image: quay.io/azavea/districtbuilder-app:${TRAVIS_COMMIT}
  geoserver:
    image: quay.io/azavea/districtbuilder-geoserver:${TRAVIS_COMMIT}
  terraform:
    build: 
      context: ./deployment
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DB_DEBUG=1
      - DB_SETTINGS_BUCKET=districtbuilder-staging-config-us-east-1
      - TRAVIS_COMMIT=${TRAVIS_COMMIT:-latest}
      - ANSIBLE_INVENTORY_FILE=${ANSIBLE_INVENTORY_FILE:-staging}
    volumes:
      - ./:/usr/local/src
      - ~/.ssh:/root/.ssh
