# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-18 21:43
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Subquery, OuterRef, Max


def forwards_func(apps, schema_editor):
    PlanSubmission = apps.get_model("redistricting", "PlanSubmission")

    latest_submissions = PlanSubmission.objects.filter(
        id=Subquery(
            PlanSubmission.objects.filter(
                submitting_user=OuterRef('submitting_user')
            ).values('id').annotate(
                latest_submission=Max('id')
            ).values('latest_submission')[:1]
        )
    ).select_related(
        'submitting_user__profile'
    )

    for submission in latest_submissions.iterator():
        profile = submission.submitting_user.profile

        if not profile.organization:
            profile.organization = submission.organization_name

        profile.county = submission.organization_name
        profile.contest_division = submission.contest_division

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0008_auto_20190118_1642'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
