# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-28 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0009_auto_20190118_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='how_did_you_hear',
            field=models.CharField(choices=[(b'TEACH', b'Teacher'), (b'FRIEN', b'Friend, Colleague'), (b'WEB_S', b'Web search'), (b'SO_ME', b'Social media'), (b'DTL_E', b'Draw the Lines event'), (b'MEDIA', b'Media coverage'), (b'EL_OF', b'Elected official'), (b'ANOTH', b'Another organization'), (b'OTHER', b'Other')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='where_did_you_hear',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
