# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0011_profile_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubmission',
            name='endorsers',
            field=models.TextField(blank=True),
        ),
    ]
