# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redistricting', '0012_plansubmission_endorsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='num_users_on_account',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
